export const ForbiddenSections = [
  "products",
  "productsCatalogue",
  "globalProducts",
  "bOfficeProducts",
  "credits",
  // "creditRequests",
  "creditsAccountsReceivable",
  "branch-offices",
  "account",
  "mainInventory",
  "mainInventory-Movements",
  "mainInventory-Outcome",
  "mainInventory-Returns",
  "mainInventory-Inventory",
  "commissions",
];
