/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://aag2lpnhpfcqtk4nl2bp35tiy4.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-ocb5nppwwre35o6jhzix76yati",
    "aws_cognito_identity_pool_id": "us-east-1:1ac8d84f-8c89-4ff8-ba98-b2e419637eb4",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_X8R4V1CDZ",
    "aws_user_pools_web_client_id": "h55g5c1qg09juttujpn4u455c",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "jaelbucket133231-test",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
